all: writer reader

writer: writer.cpp
	c++ -Wall -Werror -Wextra writer.cpp -o writer

reader: reader.cpp
	c++ -Wall -Werror -Wextra reader.cpp -o reader

clean:
	rm reader writer

.PHONY: all clean
